// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from './routes/_app.tsx'
import * as $d_hash_ from './routes/d/[hash].tsx'
import * as $index from './routes/index.tsx'
import * as $upload_sh from './routes/upload.sh.ts'
import * as $CopyButton from './islands/CopyButton.tsx'
import * as $Decrypt from './islands/Decrypt.tsx'
import * as $UploadInstructions from './islands/UploadInstructions.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_app.tsx': $_app,
    './routes/d/[hash].tsx': $d_hash_,
    './routes/index.tsx': $index,
    './routes/upload.sh.ts': $upload_sh,
  },
  islands: {
    './islands/CopyButton.tsx': $CopyButton,
    './islands/Decrypt.tsx': $Decrypt,
    './islands/UploadInstructions.tsx': $UploadInstructions,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
